function [fitresult, gof] = SR_day_smooth_filter(days_enum, mean_component)
%CREATEFIT(DAYS_ENUM,MEAN_COMPONENT)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : days_enum
%      Y Output: mean_component
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-May-2020 12:10:49


%% Fit: SmoothsplineLine for smoothing SR_day vector


%% IMPROVESMOTHLINE ALGORITHM BY PADDING
mean_add = 20;
max_day = 366; % Maximum Value (JIust in Case)

%{ IMPROVE SMOOTHLINE ALGORITHM



% mean_add values are added at the beggining of the vector
increase_days_enum = days_enum + mean_add;

% Create a vector lenght 20 of mean value of mean_componente
add_mean_samples = repmat(mean(mean_component),1,mean_add);
% Agregate values at the begging
pre_days_enum = [1:mean_add];

% Added values at the end of the vector
post_days_enum = [max_day + mean_add + 1:max_day + (2 *  mean_add)];

%Creates a vector with all the values, in TIME and VALUES
complete_days_enum = [pre_days_enum, increase_days_enum, post_days_enum];
complete_mean_component = [add_mean_samples, mean_component, add_mean_samples];

% Create a vector of the same length with NAN, 
% Improvement of the movmean algorithm

vector = NaN(1,max(complete_days_enum));
vector(complete_days_enum) = complete_mean_component;

% it is applied a mov mean filter to the vector, with the padding
F_mean = fillmissing(vector,'movmean', mean_add * 2);

smooth_values = movmean(F_mean,mean_add);


% Move Value
days = [-mean_add + 1:max_day + mean_add];


%%
[xData, yData] = prepareCurveData( days, smooth_values );


% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 6e-5;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );



