function [fitresult, gof] = fit_robust(freq, detrend_data_with_offset, weight, start_points)
%CREATEFIT(FREQ,DETREND_DATA_WITH_OFFSET,WEIGHT)
%  Create a fit.
%
%  Data for 'Sum_six_lorentz' fit:
%      X Input : freq
%      Y Output: detrend_data_with_offset
%      Weights : weight
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Apr-2020 01:19:08


%% Fit: 'Sum_six_lorentz'.
[xData, yData, weights] = prepareCurveData( freq, detrend_data_with_offset, weight );

% Set up fittype and options.
ft = fittype( 'A1/(1 + ((x - B1)/(C1/2))^2) + A2/(1 + ((x - B2)/(C2/2))^2) + A3/(1 + ((x - B3)/(C3/2))^2) + A4/(1 + ((x - B4)/(C4/2))^2) + A5/(1 + ((x - B5)/(C5/2))^2)  + A6/(1 + ((x - B6)/(C6/2))^2) + A7/(1 + ((x - B7)/(C7/2))^2)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.DiffMinChange = 1e-10;
opts.Display = 'Off';
SR_modes = [7.83, 14.3, 20.8, 27.3, 33.8, 39];
low_limit = SR_modes - 2;
opts.Lower = [-Inf -Inf -Inf -Inf -Inf -Inf -Inf low_limit -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf];
opts.MaxFunEvals = 1000;
opts.MaxIter = 1000;
opts.Robust = 'Bisquare';
opts.StartPoint = [0.399961864586141 0.0451092487106278 0.201045341699827 0.0428628361556463 0.639163201462111 0.2518 0.582986382747674 start_points 50 0.0244699833220734 0.0397795442038889 0.529818635947425 0.933367035373425 0.602214607998047 0.601176727619887 0.821353525764952];
up_limit = SR_modes + 2;
opts.Upper = [Inf Inf Inf Inf Inf Inf Inf up_limit Inf Inf Inf Inf Inf Inf Inf Inf];
opts.Weights = weights;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

%{
% Plot fit with data.
figure( 'Name', 'Sum_six_lorentz' );
h = plot( fitresult, xData, yData );
legend( h, 'detrend_data_with_offset vs. freq with weight', 'Sum_six_lorentz', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'freq', 'Interpreter', 'none' );
ylabel( 'detrend_data_with_offset', 'Interpreter', 'none' );
grid on
%}


