function [fitresult, gof] = Fits_six(freq, detrend_data_with_offset, weight, start_points)
%CREATEFIT(FREQ,DETREND_DATA_WITH_OFFSET,WEIGHT)
%  Create a fit.
%
%  Data for 'Sum_six_lorentz' fit:
%      X Input : freq
%      Y Output: detrend_data_with_offset
%      Weights : weight
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-Apr-2020 23:27:18


%% Fit: 'Sum_six_lorentz'.
[xData, yData, weights] = prepareCurveData( freq, detrend_data_with_offset', weight );
start_points = start_points(1:6);
% Set up fittype and options.
ft = fittype( 'A1/(1 + ((x - B1)/(C1/2))^2) + A2/(1 + ((x - B2)/(C2/2))^2) + A3/(1 + ((x - B3)/(C3/2))^2) + A4/(1 + ((x - B4)/(C4/2))^2) + A5/(1 + ((x - B5)/(C5/2))^2)  + A6/(1 + ((x - B6)/(C6/2))^2) + K', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Algorithm = 'Levenberg-Marquardt';
opts.DiffMinChange = 1e-10;
opts.Display = 'Off';
opts.MaxFunEvals = 1000;
opts.MaxIter = 10000;
opts.Robust = 'Bisquare';
opts.StartPoint = [0.428252992979386 0.482022061031856 0.120611613297162 0.589507484695059 0.226187679752676 0.384619124369411 start_points 0.343877004114983 0.584069333278452 0.107769015243743 0.906308150649733 0.879653724481905 0.817760559370642 0.175669029675661];
opts.Weights = weights;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );


% Plot fit with data.
figure( 'Name', 'Sum_six_lorentz' );
h = plot( fitresult, xData, yData );
legend( h, 'detrend_data_with_offset vs. freq with weight', 'Sum_six_lorentz', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'freq', 'Interpreter', 'none' );
ylabel( 'detrend_data_with_offset', 'Interpreter', 'none' );
grid on

