function [fitresult, gof] = fit_robust_6terms_limit(freq, data, weight, start_points)
%CREATEFIT(FREQ,DATA)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : freq
%      Y Output: data
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Oct-2020 20:23:21


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( freq, data );

% Set up fittype and options.
num_modes = 6;
ft = fittype( 'A1/(1 + ((x - B1)/(C1/2))^2) + A2/(1 + ((x - B2)/(C2/2))^2) + A3/(1 + ((x - B3)/(C3/2))^2) + A4/(1 + ((x - B4)/(C4/2))^2) + A5/(1 + ((x - B5)/(C5/2))^2)  + A6/(1 + ((x - B6)/(C6/2))^2)', 'independent', 'x', 'dependent', 'y' );
excludedPoints = (xData < 6) | (xData > 42);
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
SR_lower_limit = SR_config.schumann_fc(1:num_modes) - 1; 
%SR_upper_limit = SR_config.schumann_fc(1:num_modes) + 1; 
opts.Lower = [0 0 0 0 0 0 SR_lower_limit 0 0 0 0 0 0];
%opts.Upper = [0 0 0 0 0 0 SR_upper_limit 0 0 0 0 0 0];
opts.Robust = 'LAR';
opts.StartPoint = [0.183907788282417 0.239952525664903 0.41726706908437 0.0496544303257421 0.902716109915281 0.944787189721646 start_points(1:num_modes) 0.780252068321138 0.389738836961253 0.241691285913833 0.403912145588115 0.0964545251683886 0.131973292606335];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );



