function [fitresult, gof, num_modes] = fit_no_robust(freq, detrend_data_with_offset, weight, start_points)
%CREATEFIT(FREQ,DETREND_DATA_WITH_OFFSET,WEIGHT)
%  Create a fit.
%
%  Data for 'Sum_six_lorentz' fit:
%      X Input : freq
%      Y Output: detrend_data_with_offset
%      Weights : weight
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Apr-2020 14:50:38



%% Fit: 'Sum_six_lorentz'.
[xData, yData, weights] = prepareCurveData( freq, detrend_data_with_offset, weight );

num_modes = 7;
start_point_cut = start_points(1:num_modes);
% Set up fittype and options.
ft = fittype( 'A1/(1 + ((x - B1)/(C1/2))^2) + A2/(1 + ((x - B2)/(C2/2))^2) + A3/(1 + ((x - B3)/(C3/2))^2) + A4/(1 + ((x - B4)/(C4/2))^2) + A5/(1 + ((x - B5)/(C5/2))^2)  + A6/(1 + ((x - B6)/(C6/2))^2) + A7/(1 + ((x - B7)/(C7/2))^2)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
excludedPoints = (xData < 0) | (xData > 100);
opts.Algorithm = 'Levenberg-Marquardt';
opts.DiffMinChange = 1e-9;
opts.Display = 'Off';
opts.MaxFunEvals = 10000;
opts.MaxIter = 10000;
opts.Robust = 'Bisquare';
opts.StartPoint = [0.399961864586141 0.0451092487106278 0.201045341699827 0.0428628361556463 0.639163201462111 0.2518 0.582986382747674 start_point_cut  0.0244699833220734 0.0397795442038889 0.529818635947425 0.933367035373425 0.602214607998047 0.601176727619887 0.821353525764952];
%opts.StartPoint = [0.743086277968529 0.0654391063163385 0.733467195209203 0.761148756910362 0.403787453904642 0.849094421074692 0.611956112266734 8 14 20 28 33 39 45 0.745086391298769 0.690316618981957 0.764789143062757 0.41130003909715 0.58951157318545 0.200345126681855 0.93599174999282];
opts.Weights = weights;
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
%{
figure( 'Name', 'Levenberg_seven' );
h = plot( fitresult, xData, yData );
legend( h, 'detrend_data_with_offset vs. freq with weight', 'Sum_six_lorentz', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'freq', 'Interpreter', 'none' );
ylabel( 'detrend_data_with_offset', 'Interpreter', 'none' );
grid on
%}

