function y = test_lpf(x)
%  Preprocess input x
%    This function expects an input vector x.

% Generated by MATLAB(R) 9.7 and Signal Processing Toolbox 8.3.
% Generated on: 29-Oct-2020 14:48:07

y = lowpass(x,0.3,'Steepness',0.85,'StopbandAttenuation',60);
y = lowpass(y,0.3,'Steepness',0.85,'StopbandAttenuation',60);